- name: cvmfs
  hosts: cvmfsstratum0servers
  become: true
  vars_files:
    - group_vars/global.yml
  vars:
    cvmfs_role: stratum0
    cvmfs_server_urls:
      - domain: "{{ galaxy_host }}"
        urls:
          - "http://{{ cvmfs0_host }}/cvmfs/@fqrn@"
    cvmfs_repositories:
      - repository: "data.{{ galaxy_host }}"
        stratum0: "{{ cvmfs0_host }}"
        key_dir: "/etc/cvmfs/keys/{{ galaxy_host }}"
        server_options:
          - CVMFS_AUTO_TAG=false
          - CVMFS_GARBAGE_COLLECTION=true
          - CVMFS_AUTO_GC=false
        client_options:
          - CVMFS_NFILES=4096
  roles:
    - galaxyproject.cvmfs
