- name: Create ssh dir
  file:
    dest: "~{{ galaxy_user.name }}/.ssh/"
    state: directory
    owner: "{{ galaxy_user.name }}"
    group: "{{ galaxy_user.name }}"
    mode: "0700"
- name: Add NeLS storage IDs to known_hosts
  become: true
  become_user: "{{ galaxy_user.name }}"
  known_hosts:
    name: "{{ item.name }}"
    key: "{{ item.key }}" # some key gibberish
    state: present
  with_items: "{{ vault_ssh_known_hosts|default([]) }}"
  ignore_errors: True

- name: set hostname
  hostname:
    name: "{{inventory_hostname}}"


# Dont like this, but works for now
#- name: create dynamic slurm node list (debug)
#  debug:
#    msg: "{{ item }}"
#    msg: "{{ hostvars[ item ].ansible_processor_cores }}"
#    msg: "{{ hostvars[ item ].ansible_processor_count }}"
#    msg: "{{ hostvars[ item ].ansible_processor_threads_per_core }}"
#    msg: "{{ hostvars[ item ].ansible_processor_vcpus }}"
#    msg: "{{ hostvars[ item ].ansible_memtotal_mb }}"
#  with_items: "{{ groups['slurm'] }}"


# Dont like this, but works for now
- name: create dynamic slurm node list
  set_fact:
    slurm_nodes: "{{ slurm_nodes|default([]) + [ {'name': item,
                                                  'CoresPerSocket': hostvars[ item ].ansible_processor_cores,
                                                  'Sockets': hostvars[ item ].ansible_processor_count,
                                                  'ThreadsPerCore':  hostvars[ item ].ansible_processor_threads_per_core,
                                                  'CPUs': hostvars[ item ].ansible_processor_vcpus,
                                                  'NodeAddr': hostvars[ item ].ansible_host,
                                                  'RealMemory': hostvars[ item ].ansible_memtotal_mb} ] }}"

  with_items: "{{ groups['slurm'] }}"

# Hostname: item, ip addr: hostvars[item]['ansible_host']


