- name: systemd status script
  copy:
    src: files/bin/systemd_status.py
    dest: /usr/local/bin/systemd_status.py
    mode: '0755'
    owner: root
    group: root
    backup: yes

- name: httpd status script
  copy:
    src: files/bin/http_status.py
    dest: /usr/local/bin/http_status.py
    mode: '0755'
    owner: root
    group: root
    backup: yes

- name: dir/file status script
  copy:
    src: files/bin/dir_status.py
    dest: /usr/local/bin/dir_status.py
    mode: '0755'
    owner: root
    group: root
    backup: yes

- name: copy postfix main.cf
  when: ansible_nodename == 'db.usegalaxy.no'
  template:
    src: files/system/postfix_main.cf.j2
    dest: /etc/postfix/main.cf
    mode: '0644'
    owner: root
    group: root

- name: set mailname
  when: ansible_nodename == 'db.usegalaxy.no'
  lineinfile:
    path: /etc/mailname
    line: usegalaxy.no
    owner: root
    group: root
    mode: '0644'

- name: restart postfix
  when: ansible_nodename == 'db.usegalaxy.no'
  service:
    name: postfix
    state: restarted
    enabled: yes

- name: increase number of nfs server processes
  when: ansible_nodename == 'usegalaxy.no'
  lineinfile:
    state: present
    path: /etc/sysconfig/nfs
    regexp: '(.*RPCNFSDCOUNT=.*)'
    line: RPCNFSDCOUNT=64

- name: restart nfsd
  when: ansible_nodename == 'usegalaxy.no'
  service:
    name: nfs-server
    state: restarted
    enabled: yes
