rabbitmq_version: "3.8.6"
rabbitmq_rpm: "rabbitmq-server-{{ rabbitmq_version }}-1.el{{ ansible_distribution_major_version }}.noarch.rpm"
rabbitmq_rpm_url: "https://packagecloud.io/rabbitmq/rabbitmq-server/packages/el/{{ ansible_distribution_major_version }}/{{ rabbitmq_rpm }}/download"

rabbitmq_host: "{{ groups['rabbitmq'][0] }}"

rabbitmq_vhosts:
  - test
  - nels_galaxy
  - galaxy_internal

rabbitmq_users:
  - {name: admin,  vhost: '/', 
     passwd: "{{vault_admin_rabbitmq_password}}", tags: administrator}
  - {name: test, vhost: test, 
     passwd: "{{vault_rabbitmq_password_galaxy_test}}" }
  - {name: telegraf, vhost: '/',
     passwd: "{{vault_telegraf_rabbitmq_password}}", tags: monitoring }
  - {name: nels_galaxy, vhost: 'nels_galaxy',
     passwd: '{{vault_rabbitmq_password_nels_galaxy_api}}'}
  - {name: galaxy, vhost: 'galaxy_internal',
     passwd: '{{vault_rabbitmq_password_galaxy}}'}
  - {name: flower, vhost: 'galaxy_internal',
     passwd: '{{vault_rabbitmq_password_flower}}', tags: administrator}
